# Generated by Django 4.2 on 2023-05-02 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0002_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('start_line', models.IntegerField()),
                ('end_line', models.IntegerField()),
                ('status_data', models.CharField(blank=True, max_length=1000)),
                ('source_code', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
                ('section_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.sectionstatus')),
                ('section_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.sectiontype')),
            ],
        ),
    ]
