# Generated by Django 4.2 on 2023-05-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_sectionstatus_sectiontype_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='status_data',
            field=models.TextField(),
        ),
    ]
